// <auto-generated />
using System;
using Drivers.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Drivers.Migrations
{
    [DbContext(typeof(DriverContext))]
    [Migration("20230627203035_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("Drivers.Models.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverLicense")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PostCode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SSN")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.HasKey("DriverId");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            DriverId = 1,
                            Address = "NY",
                            DateOfBirth = new DateTime(1989, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverLicense = "",
                            Email = "",
                            FirstName = "Johnson",
                            LastName = "Mitchel",
                            Phone = "1221221221",
                            SSN = 2353453
                        },
                        new
                        {
                            DriverId = 2,
                            Address = "Sydney",
                            DateOfBirth = new DateTime(1992, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverLicense = "",
                            Email = "",
                            FirstName = "Mitchel",
                            LastName = "Strac",
                            Phone = "2121212121",
                            SSN = 456435
                        },
                        new
                        {
                            DriverId = 3,
                            Address = "Brisbane",
                            DateOfBirth = new DateTime(1990, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverLicense = "",
                            Email = "",
                            FirstName = "Breet",
                            LastName = "Lee",
                            Phone = "7676767676",
                            SSN = 23123234
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
